#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.2.0@rails4.2/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.2.0@rails4.2/environment"
  exec nokogiri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.2.0@rails4.2/environment'" >&2
  exit 1
fi
