#!/usr/bin/env bash

if
  [[ -s "/home/action/.gem/ruby/2.1.1/environment" ]]
then
  source "/home/action/.gem/ruby/2.1.1/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.gem/ruby/2.1.1/environment'" >&2
  exit 1
fi
